### ISSUE TITLE
Include Request with FromFormAttribute to be able to send files

### ISSUE THREAD

**Issue by VFA91** [Xabaril/Acheve.TestHost#22]
Hello, it does not allow to invoke an endpoint with the [FromForm] attribute.

I have built a solution so that I can support this feature.

Is it possible to get access to upload the code?

Regards, Vicente.

**Comment by VFA91** [comment]
https://github.com/VFA91/Acheve.TestHost/commit/7064e24c67208ad1cb3ebbba78036a6154acf1e0

**Comment by hbiarge** [comment]
Hi Vicente!
Thanks for reporting this issue!

I´m reviewing the pull request.
I have some doubts and comments to add there ;)

**Comment by VFA91** [comment]
Tell me, I do not know if the implementation is correct

**Comment by hbiarge** [comment]
FIxed in #23
