### ISSUE TITLE
Use CancellationToken in Controllers

### ISSUE THREAD

**Issue by serweck** [Xabaril/Acheve.TestHost#70]
Acheve can't call methods with CancellationToken

**Comment by Sergio1192** [comment]
Hello! You can use HttpContext.RequestAbort to avoid this problem with the same funcionality.
[https://github.com/aspnet/Mvc/issues/5239](https://github.com/aspnet/Mvc/issues/5239)

**Comment by serweck** [comment]
it's working with this. Thx Sergio :)
