### ISSUE TITLE
Controller methods' implemented through an interface don't work

### ISSUE THREAD

**Issue by juanDeVicente** [Xabaril/Acheve.TestHost#71]
The interface method is marked with flags "virtual" and "abstract" and this method dont validate this case
![image](https://user-images.githubusercontent.com/23058607/182311729-a7b06a90-c914-4787-8057-a44c7d1cffca.png)
![image](https://user-images.githubusercontent.com/23058607/182313017-1408ecad-92b4-4059-85ad-f789139d72bb.png)
Maybe it can be fixed checking if method is abstract and not virtual?

**Comment by Sergio1192** [comment]
It will be added in the new version :)
