### ISSUE TITLE
Cannot test post actions with CancellationToken

### ISSUE THREAD

**Issue by dgarciarubio** [Xabaril/Acheve.TestHost#73]
Currently it is not possible to test post actions that get a cancellationToken injected such as the following:

```csharp
    [HttpPost]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public IActionResult Create([FromBody] Model data, CancellationToken cancellationToken)
    {
        return Ok();
    }
```

This is due to the TestServerAction assuming that any parameter without a `[FromXXX]` attribute comes from the body:
https://github.com/Xabaril/Acheve.TestHost/blob/29fd1cae71c9c494683aad2042dcaa304de405a5/src/Acheve.TestHost/Routing/TestServerAction.cs#L35

Then the method `AddFromBodyArgumentsToRequestBody` from `TestServerExtensions` expects a single parameter from the Body:
https://github.com/Xabaril/Acheve.TestHost/blob/22a20970dac172c09db8abbccdaefa0f4db5f9af/src/Acheve.TestHost/TestServerExtensions.cs#L170

So in this results in a `System.InvalidOperationException : Sequence contains more than one matching element`

I don't know if anything can be done to detect such cases. I assume there could be similar issues as well with services injected in actions with the `[FromServices]` attribute, though I haven't tested it.

**Comment by Sergio1192** [comment]
Hello @dgarciarubio!

You can use HttpContext.RequestAbort to avoid this problem with the same funcionality.
[https://github.com/aspnet/Mvc/issues/5239](https://github.com/aspnet/Mvc/issues/5239)

Also, in the future, we want to add this functionality :)
